version: "3.7"
services:
  postgis:
    image: geographica/postgis:dev_diplodocus
    ports:
      - "5432:5432"
    volumes:
      - db-data:/data
    environment:
      - POSTGRES_PASSWD=postgres
  api:
    build:
      context: .
    command: local
    env_file:
      - ././server/.env
    volumes:
      - db-data:/data
    ports:
      - "8000:8000"
    depends_on:
      - postgis

volumes:
  db-data:
